# --------- Mandatory Configurations --------- #
SERIAL_PORT: 'COM3'

# log file name date format
DATE_FORMAT: 'YYYY_MMM_DD'

# log messages timestamp format
DATETIME_FORMAT: 'YYYY-MMM-DD HH:mm:ss'

# CHECK_INTERVAL must be a fraction of COLLECTION_TIME
CHECK_INTERVAL: 60  # seconds

# default collection time
COLLECTION_TIME_DEFAULT: 180  # minutes


# ---------- Optional Configurations --------- #
optional:
  # NB: any optional config must be indented by 2 spaces.
  # collection time for a specific position can be set using the format COLLECTION_TIME_POS_N
  COLLECTION_TIME_POS_1: 60  # minutes
